# Generated by Django 6.0.6 on 2026-06-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ['id'], 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
    ]
